<a href="https://colab.research.google.com/github/Souravkumar2434/Machine_learning/blob/main/pytorch_demo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__


'2.6.0+cu124'

In [4]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"GPU name is {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, using CPU")

GPU is available
GPU name is Tesla T4


In [5]:
# creating an empty tensor using pytorch

torch.empty(2, 4)

tensor([[0.0000e+00, 0.0000e+00, 8.8519e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
# check type of tensor
type(torch.empty(2, 3))

torch.Tensor

In [7]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones(4, 1)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [9]:
torch.rand(5, 6)

tensor([[0.7274, 0.3195, 0.9567, 0.0971, 0.4338, 0.4132],
        [0.5009, 0.8081, 0.4839, 0.0716, 0.6331, 0.1743],
        [0.6830, 0.9261, 0.9150, 0.4484, 0.6282, 0.0575],
        [0.0340, 0.2204, 0.0144, 0.5924, 0.2930, 0.6226],
        [0.9970, 0.8403, 0.8859, 0.5148, 0.8419, 0.3093]])

In [12]:
# used to get consistent output using rand
torch.manual_seed(100)
torch.rand(5, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023]])

In [13]:
torch.tensor([i for i in range(1, 10)])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.arange(2, 10)

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.arange(2, 10, 2)

tensor([2, 4, 6, 8])

In [18]:
torch.linspace(2, 10, 6)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])

In [19]:
# creating an identity matrix
torch.eye(5, 6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [21]:
# creating a full matrix
torch.full((3, 4), 2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [23]:
# tensor shapes
x = torch.tensor([[1, 2], [3, 5]])

In [24]:
x.shape

torch.Size([2, 2])

In [25]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286],
        [8367752027310484831, 7954801838398993778]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

In [28]:
torch.rand_like(x, dtype = float)

tensor([[0.4274, 0.4460],
        [0.5522, 0.9559]], dtype=torch.float64)

In [29]:
# find datatypes of tensor

x.dtype

torch.int64

In [30]:
# change datatype of tensor

x.to(dtype=torch.float64)

tensor([[1., 2.],
        [3., 5.]], dtype=torch.float64)